/*
 * @Author: Nero
 * @Github: https://github.com/nero90011
 * @E-mail: 601412402@qq.com
 * @Company: myself
 * @Date: 2020-04-25 12:55:43
 * @LastEditTime: 2020-04-25 15:09:48
 * @LastEditors: Do not edit
 * @Description: 
 */
// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"


export interface Order {
    id:           number;
    uuid:         string;
    uid:          number;
    comid:        null;
    money:        number;
    location:     string;
    status:       number;
    susername:    string;
    sid:          number;
    num:          number;
    choose:       string;
    cid:          number;
    title:        string;
    img:          string;
    onemoney:     number;
    created:      string;
    updatedOn:    string;
    deletionDate: null;
}
