/*
 * @Author: Nero
 * @Github: https://github.com/nero90011
 * @E-mail: 601412402@qq.com
 * @Company: myself
 * @Date: 2020-04-02 16:14:55
 * @LastEditTime: 2020-04-02 16:14:57
 * @LastEditors: Do not edit
 * @Description:
 */
// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Data {
    name: string;
    price: number;
    number: number;
    id: number;
}
