// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Data1 {
  msg: string;
  status: number;
  data: Data;
}

export interface Data {
  cinemas: Cinema[];
  comingList: ComingList[];
  cities: City[];
}

export interface Cinema {
  id: number;
  mark: number;
  nm: string;
  sellPrice: string;
  addr: string;
  distance: string;
  tag: Tag;
  promotion: Promotion;
  showTimes: string;
}

export interface Promotion {
  cardPromotionTag: string;
  couponPromotionTag: string;
  merchantActivityTag: string;
  packShowActivityTag: string;
  platformActivityTag: string;
  starActivityTag: string;
}

export interface Tag {
  allowRefund: number;
  buyout: number;
  cityCardTag: number;
  deal: number;
  endorse: number;
  giftTag: string;
  hallType: string[];
  hallTypeVOList: HallTypeVOList[];
  sell: number;
  snack: number;
  vipTag: VipTag;
}

export interface HallTypeVOList {
  name: string;
  url: string;
}

export enum VipTag {
  折扣卡 = '折扣卡'
}

export interface City {
  id: number;
  nm: string;
  isHot: number;
  py: string;
}

export interface ComingList {
  id: number;
  haspromotionTag: boolean;
  img: string;
  version: string;
  nm: string;
  preShow: boolean;
  sc: number;
  globalReleased: boolean;
  wish: number;
  star?: string;
  rt: string;
  showst: number;
  wishst: number;
  comingTitle: string;
}
